# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 23:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import ponto.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHorária',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ano', models.IntegerField()),
            ],
            options={
                'ordering': ['ano'],
            },
            bases=(ponto.utils.CalculadoraTempoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dia', models.IntegerField()),
                ('dia_semana', models.IntegerField(choices=[(6, 'Domingo'), (5, 'Sábado'), (4, 'Sexta-feira'), (3, 'Quinta-feira'), (2, 'Quarta-feira'), (1, 'Terça-feira'), (0, 'Segunda-feira')])),
                ('entrada_manhã', models.TimeField(default=datetime.time(0, 0))),
                ('saída_manhã', models.TimeField(default=datetime.time(0, 0))),
                ('entrada_tarde', models.TimeField(default=datetime.time(0, 0))),
                ('saída_tarde', models.TimeField(default=datetime.time(0, 0))),
                ('observação', models.TextField()),
            ],
            options={
                'ordering': ['dia'],
            },
            bases=(ponto.utils.CalculadoraTempoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MêsTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mês', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('carga_horária', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meses', to='ponto.CargaHorária')),
            ],
            options={
                'ordering': ['mês'],
            },
            bases=(ponto.utils.CalculadoraTempoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('siape', models.CharField(max_length=16)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='diatrabalho',
            name='mês_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='ponto.MêsTrabalho'),
        ),
        migrations.AddField(
            model_name='cargahorária',
            name='ponto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_horária', to='ponto.Ponto'),
        ),
    ]
