# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargahorária',
            options={'ordering': ['ano']},
        ),
        migrations.AlterModelOptions(
            name='diatrabalho',
            options={'ordering': ['dia']},
        ),
        migrations.AlterModelOptions(
            name='mêstrabalho',
            options={'ordering': ['referência']},
        ),
        migrations.AlterModelOptions(
            name='ponto',
            options={'ordering': ['id']},
        ),
    ]
