# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_auto_20180106_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diatrabalho',
            old_name='mês',
            new_name='mês_trabalho',
        ),
    ]
